workflows:
  ios-release:
    name: iOS Release (DogPark JP)
    instance_type: mac_mini_m2
    max_build_duration: 60

    # ← ここで “どの App Store Connect 接続を使うか” を指定します
    integrations:
      app_store_connect: __PASTE_INTEGRATION_ID__

    environment:
      xcode: 15.4
      node: 20.11.1
      cocoapods: default
      vars:
        BUNDLE_ID: com.dogparkjp.app
        APPLE_TEAM_ID: 9HT7A6UF4K
        IOS_SCHEME: App

    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods
        - ios/Pods

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      - name: Install JS deps
        script: |
          npm ci --legacy-peer-deps

      - name: Build web
        script: |
          npm run build

      - name: Add/Sync Capacitor iOS platform
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod repo update
          pod install

      - name: Bump build number (must be > previous one)
        script: |
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $(date +%s)" "ios/App/App/Info.plist"

      - name: Build archive & IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme "$IOS_SCHEME" \
            --config Release \
            --export-method app-store

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
