workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        # Xcode/Capacitor の基本情報
        IOS_WORKSPACE: "ios/App/App.xcworkspace"   # ← 違う場合は変更
        IOS_SCHEME: "App"                           # ← Xcode の Scheme 名
        BUNDLE_ID: "com.dogparkjp.app"              # ← 実際の Bundle ID
        # 手動署名を使う場合に参照する（Codemagic 側に証明書&プロファイルを登録しておく）
        DEVELOPMENT_TEAM_PROD: "9HT7A6UF4K"         # ← Apple Developer Team ID
        IOS_PROVISIONING_PROFILE: "dogparkjp_app_store_v2"  # ← プロファイル名
      xcode: latest
      cocoapods: default
      node: 20
      npm: 10

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      # 1) Node 依存の解決 & Webビルド
      - name: Install JS deps & build web
        script: |
          npm ci --legacy-peer-deps
          npx vite build

      # 2) Capacitor 同期（iOS プロジェクト生成/更新）
      - name: Sync Capacitor iOS platform
        script: |
          npx cap sync ios

      # 3) CocoaPods インストール
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod repo update
          pod install
          cd "$CM_BUILD_DIR"

      # 4) （任意）ビルド番号を自動で +1
      - name: Bump iOS build number (CFBundleVersion +1)
        script: |
          plist="ios/App/App/Info.plist"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $(($(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$plist") + 1))" "$plist"
          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$plist"

      # 5) 署名プロファイルをプロジェクトへ適用（手動署名）
      - name: Apply profiles (manual signing)
        script: |
          xcode-project use-profiles \
            --code-signing-style Manual \
            --team-id "$DEVELOPMENT_TEAM_PROD"

      # 6) アーカイブ & IPA 作成（Xcodeが見つけられるよう generic iOS Destination 指定）
      - name: Build archive & IPA
        script: |
          xcode-project build-ipa \
            --workspace "$IOS_WORKSPACE" \
            --scheme "$IOS_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        # ← Codemagic の Environment variables に登録しておく
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        private_key: $APP_STORE_CONNECT_PRIVATE_KEY

        # まずはアップロードのみ（後からTestFlight/審査提出に切替可）
        submit_to_app_store: false
        submit_to_testflight: false

        ipa_path: "build/ios/ipa/*.ipa"
