workflows:
  ios-release:
    name: iOS App Store (Capacitor/Ionic)
    max_build_duration: 60
    instance_type: mac_mini_m1

    integrations:
      app_store_connect: "DogParkJP API Key"

    environment:
      xcode: latest
      cocoapods: default
      node: 20
      vars:
        APP_NAME: "DogPark JP"
        BUNDLE_ID: "com.dogparkjp.app"
        DEVELOPMENT_TEAM: "9HT7A6UF4K"
        PROFILE_NAME: "dogparkjp_app_store_v2"
      groups:
        - supabase
        - codesign

    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - ios/App/Pods
        - ~/.npm

    scripts:
      - name: Show versions
        script: |
          echo "Node: $(node -v)"
          echo "NPM:  $(npm -v)"
          echo "Xcode: $(xcodebuild -version)"

      - name: Install dependencies
        script: npm ci --legacy-peer-deps

      - name: Build web assets
        script: npm run build

      - name: Ensure iOS platform exists
        script: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod repo update
          pod install

      - name: Inspect installed certs & profiles (debug)
        script: |
          echo "== Identities ==" && security find-identity -v -p codesigning || true
          echo "== Provisioning Profiles ==" && ls -la "$HOME/Library/MobileDevice/Provisioning Profiles/" || true

      - name: Fetch profiles & import certs
        script: |
          keychain i
