workflows:
  ios-release:
    name: iOS Release (DogPark JP)
    instance_type: mac_mini_m2
    max_build_duration: 60

    # ← ここで App Store Connect の Integration を紐づけます
    integrations:
      app_store_connect: d5ac3012-7133-4adb-afbf-b204d7abc83c

    environment:
      xcode: 15.4
      node: 20.11.1
      cocoapods: default
      vars:
        BUNDLE_ID: com.dogparkjp.app
        APPLE_TEAM_ID: 9HT7A6UF4K
        IOS_SCHEME: App

    # Integration 認証を使うのがポイント（api_key ではない）
    publishing:
      app_store_connect:
        auth: integration

    scripts:
      - name: Install JS deps
        script: |
          npm ci --legacy-peer-deps

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Bump iOS build number (CFBundleVersion)
        script: |
          agvtool new-version -all $BUILD_NUMBER

      - name: Build IPA with Xcode
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme "$IOS_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - ~/Library/Developer/Xcode/Archives/**/*
