workflows:
  ios-release:
    name: iOS Release (DogPark JP)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 15.4
      node: 20.11.1
      cocoapods: default
      vars:
        BUNDLE_ID: com.dogparkjp.app
        APPLE_TEAM_ID: 9HT7A6UF4K
        IOS_SCHEME: App
      # ← ここが重要：APIキーを入れてある “appstore_connect” グループを読み込む
      groups:
        - appstore_connect
        # 証明書/p12等を使う場合は codesign グループも（無ければこの行は消してOK）
        - codesign

    scripts:
      - name: Install JS deps
        script: |
          npm ci --legacy-peer-deps

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Bump iOS build number (CFBundleVersion)
        script: |
          if [ -d "ios/App" ]; then
            agvtool new-version -all $BUILD_NUMBER
          else
            echo "iOS project not found, skip agvtool"
          fi

      - name: Build IPA with Xcode
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme "$IOS_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - ~/Library/Developer/Xcode/Archives/**/*

    publishing:
      app_store_connect:
        # ← ここが重要：integration ではなく APIキー方式を明示
        auth: api_key
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
        beta_groups:
          - Internal Testing
