workflows:
  ios-release:
    name: iOS Release (DogPark JP)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 15.4
      node: 20.11.1
      cocoapods: default
      vars:
        BUNDLE_ID: com.dogparkjp.app
        APPLE_TEAM_ID: 9HT7A6UF4K
        IOS_SCHEME: App

    # ※ まずはビルドを通すため、公開(アップロード)設定は後で追加します
    # publishing:
    #   app_store_connect:
    #     auth: integration
    #     integration: YOUR_INTEGRATION_ID  # ← 後で差し込む

    scripts:
      - name: Install JS deps
        script: |
          npm ci --legacy-peer-deps

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: CocoaPods install (safety)
        script: |
          cd ios/App
          pod install --repo-update
          cd ../..

      - name: Bump iOS build number (CFBundleVersion)
        script: |
          agvtool new-version -all $BUILD_NUMBER

      - name: Build IPA with Xcode (auto-detect workspace/project)
        script: |
          # ワークスペース/プロジェクト自動検出して IPA を作成
          if ls ios/App/*.xcworkspace 1> /dev/null 2>&1; then
            xcode-project build-ipa \
              --workspace ios/App/*.xcworkspace \
              --scheme "$IOS_SCHEME"
          else
            xcode-project build-ipa \
              --project ios/App/*.xcodeproj \
              --scheme "$IOS_SCHEME"
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - ~/Library/Developer/Xcode/Archives/**/*
