workflows:
  ios-release:
    name: iOS App Store (Capacitor/Ionic)
    max_build_duration: 60
    instance_type: mac_mini_m1

    integrations:
      app_store_connect: "DogParkJP API Key"

    environment:
      xcode: latest
      cocoapods: default
      node: 20
      vars:
        BUNDLE_ID: com.dogparkjp.app
        APP_NAME: DogPark Japan
        DEVELOPMENT_TEAM: 9HT7A6UF4K
      groups:
        - supabase
        - codesign

    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - ios/App/Pods
        - ~/.npm

    scripts:
      - name: Show versions
        script: |
          echo "Node: $(node -v)"
          echo "NPM : $(npm -v)"

      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps

      - name: Build web assets (Vite)
        script: |
          npm run build

      - name: Ensure iOS platform exists
        script: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod repo update
          pod install

      # （確認用）現在の証明書／プロファイルの可視化
      - name: Inspect installed certs & profiles
        script: |
          echo "== Identities =="
          security find-identity -v -p codesigning || true
          echo "== Provisioning Profiles (before) =="
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles/" || true

      # App Store Connect から必要なプロファイルを取得（無ければ作成）＋ p12 取込み
      - name: Fetch profiles & import certs
        script: |
          set -e
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          echo "== Provisioning Profiles (after fetch) =="
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles/" || true

      # 取得したプロファイルを Xcode プロジェクトへ反映
      - name: Apply profiles to Xcode project
        script: |
          set -e
          xcode-project use-profiles

      # サポートの提案：archive-flags だけ指定。export-method は付けない
      - name: Build IPA with Xcode (after use-profiles)
        script: |
          set -euo pipefail
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App" \
            --archive-flags="-destination 'generic/platform=iOS'"

      # 実際のビルド設定確認
      - name: Show effective build settings (provisioning)
        script: |
          set -o pipefail
          xcodebuild -workspace ios/App/App.xcworkspace -scheme App -showBuildSettings | \
            grep -E "PRODUCT_BUNDLE_IDENTIFIER|DEVELOPMENT_TEAM|CODE_SIGN_STYLE|PROVISIONING_PROFILE_SPECIFIER|PROVISIONING_PROFILE" || true

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Logs/gym/*.log
      - $CM_BUILD_DIR/ios/App/build/**/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
