workflows:
  ios-release:
    name: iOS Release (DogPark JP)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 15.4
      node: 20.11.1
      cocoapods: default
      vars:
        BUNDLE_ID: com.dogparkjp.app
        APPLE_TEAM_ID: 9HT7A6UF4K
        IOS_SCHEME: App
      groups:
        - supabase
        - codesign

    integrations:
      app_store_connect: "DogParkJP API Key"

    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods
        - ios/App/Pods

    scripts:
      - name: Install JS deps & build web
        script: |
          set -e
          if [ -f package-lock.json ]; then
            npm ci --legacy-peer-deps
          else
            npm install --legacy-peer-deps
          fi
          npm run build || npx vite build

      - name: Ensure Capacitor iOS platform & sync
        script: |
          set -e
          npx cap add ios || true
          npx cap sync ios

      - name: CocoaPods install
        script: |
          set -e
          cd ios/App
          pod repo update || true
          pod install
          cd -

      - name: Fetch signing files & configure keychain
        script: |
          set -e
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      - name: Build IPA (app-store-connect)
        script: |
          set -euo pipefail
          IPA_DIR="build/ios/ipa"
          mkdir -p "$IPA_DIR"
          rm -rf ~/Library/Developer/Xcode/DerivedData/* || true

          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme "$IOS_SCHEME" \
            --archive-flags "CURRENT_PROJECT_VERSION=$BUILD_NUMBER DEVELOPMENT_TEAM=$APPLE_TEAM_ID" \
            --export-method app-store-connect

    artifacts:
      - build/ios/ipa/*.ipa
      - ~/Library/Developer/Xcode/Archives/**/*

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
