workflows:
  ios-release:
    name: iOS App Store (Capacitor/Ionic)
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: "DogParkJP API Key"
    environment:
      xcode: latest
      cocoapods: default
      node: 20
      vars:
        BUNDLE_ID: com.dogparkjp.app
        APP_NAME: DogPark Japan
        DEVELOPMENT_TEAM: 9HT7A6UF4K
      groups:
        - supabase
        - codesign
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - ios/App/Pods
        - ~/.npm
    scripts:
      - name: Show versions
        script: |
          echo "Node: $(node -v)"
          echo "NPM:  $(npm -v)"
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps
      - name: Build web assets (Vite)
        script: |
          npm run build
      - name: Ensure iOS platform exists
        script: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod repo update
          pod install
      - name: Install provisioning profiles and certificates
        script: |
          # キーチェーン初期化
          keychain initialize
          # プロファイルだけ取得（証明書は取得しない）
          app-store-connect fetch-profiles --type IOS_APP_STORE --bundle-id "$BUNDLE_ID" --create
          # 環境変数 CM_KEYCHAIN_CERTIFICATES に登録した p12 を取り込み
          keychain add-certificates
          # 取得したプロファイルを Xcode プロジェクトへ適用
          xcode-project use-profiles
      - name: Show signing settings (debug)
        script: |
          xcode-project show-build-settings --workspace "ios/App/App.xcworkspace" --scheme "App" | grep -E "PRODUCT_BUNDLE_IDENTIFIER|DEVELOPMENT_TEAM|CODE_SIGN_STYLE|PROVISIONING_PROFILE_SPECIFIER|PROVISIONING_PROFILE" || true
      - name: Build IPA with Xcode (Automatic signing)
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App" \
            --archive-flags="DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM CODE_SIGN_STYLE=Automatic -destination 'generic/platform=iOS'"
      - name: Show effective build settings (provisioning)
        script: |
          set -o pipefail
          xcodebuild -workspace ios/App/App.xcworkspace -scheme App -showBuildSettings | grep -E "PRODUCT_BUNDLE_IDENTIFIER|DEVELOPMENT_TEAM|CODE_SIGN_STYLE|PROVISIONING_PROFILE_SPECIFIER|PROVISIONING_PROFILE" || true
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Logs/gym/*.log
      - $CM_BUILD_DIR/ios/App/build/**/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
