workflows:
  ios-release:
    name: iOS Release (DogPark JP)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 15.4
      node: 20.11.1
      cocoapods: default

      groups:
        - appstore_connect   # ← APP_STORE_CONNECT_* の3つが入っているグループ

      vars:
        BUNDLE_ID: com.dogparkjp.app
        APPLE_TEAM_ID: 9HT7A6UF4K
        IOS_SCHEME: App

    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods
        - ios/Pods

    scripts:
      - name: Install JS deps & build web
        script: |
          npm ci --legacy-peer-deps
          npm run build || npx vite build || true

      - name: Ensure Capacitor iOS platform & sync
        script: |
          npx cap add ios || true
          npx cap sync ios

      - name: CocoaPods install (safety)
        script: |
          cd ios/App
          pod repo update || true
          pod install

      - name: Bump iOS build number (CFBundleVersion)
        script: |
          if [ -d "ios/App/App.xcworkspace" ] || [ -d "ios/App/App.xcodeproj" ]; then
            agvtool new-version -all "$BUILD_NUMBER"
          else
            echo "No Xcode project found, skipping agvtool."
          fi

      - name: Build IPA with Xcode
        script: |
          set -e
          if [ -d "ios/App/App.xcworkspace" ]; then
            xcode-project build-ipa \
              --workspace ios/App/App.xcworkspace \
              --scheme "$IOS_SCHEME" \
              --archive-flags "-destination generic/platform=iOS"
          elif [ -d "ios/App/App.xcodeproj" ]; then
            xcode-project build-ipa \
              --project ios/App/App.xcodeproj \
              --scheme "$IOS_SCHEME" \
              --archive-flags "-destination generic/platform=iOS"
          else
            echo "No Xcode project under ios/App/"
            exit 1
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - ~/Library/Developer/Xcode/Archives/**/*

    publishing:
      app_store_connect:
        # ← ここが決定打：フィールド名は api_key / key_id / issuer_id
        auth: api_key
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY   # .p8 を Base64 化した文字列
        key_id: $APP_STORE_CONNECT_KEY_ID         # 例: JJVYI33PUOYU
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID   # 例: d5ac3012-7133-4adb-afbf-b204d7abc83c
        submit_to_testflight: true
