workflows:
  ios-release:
    name: iOS App Store (Capacitor/Ionic)
    max_build_duration: 60
    instance_type: mac_mini_m1

    integrations:
      app_store_connect: "DogParkJP API Key"

    environment:
      xcode: latest
      cocoapods: default
      node: 20
      vars:
        BUNDLE_ID: com.dogparkjp.app
        APP_NAME: DogPark Japan
        DEVELOPMENT_TEAM: 9HT7A6UF4K
        PROFILE_NAME: dogparkjp_app_store_v2
      groups:
        - supabase
        - codesign

    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - ios/App/Pods
        - ~/.npm

    scripts:
      - name: Show versions
        script: |
          echo "Node: $(node -v)"
          echo "NPM:  $(npm -v)"

      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps

      - name: Build web assets (Vite)
        script: |
          npm run build

      - name: Ensure iOS platform exists
        script: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod repo update
          pod install

      # ---- デバッグ: いま入っている証明書/プロファイルの見える化 ----
      - name: Inspect installed certs & profiles
        script: |
          echo "== Identities =="
          security find-identity -v -p codesigning || true
          echo "== Provisioning Profiles =="
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles/" || true

      # ---- App Store Connect から必要なプロファイル/証明書を取得（無ければ作成）----
      - name: Fetch profiles & import certs
        script: |
          set -euo pipefail
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates

      # ---- ExportOptions.plist を作成（App Store 用）----
      - name: Create ExportOptions.plist
        script: |
          cat > "$CM_BUILD_DIR/export_options.plist" <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>uploadBitcode</key>
            <false/>
            <key>compileBitcode</key>
            <false/>
            <key>signingStyle</key>
            <string>manual</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>destination</key>
            <string>export</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.dogparkjp.app</key>
              <string>dogparkjp_app_store_v2</string>
            </dict>
          </dict>
          </plist>
          EOF
          echo "=== ExportOptions.plist ==="
          cat "$CM_BUILD_DIR/export_options.plist"

      # ---- アーカイブ（詳細ログ保存＆エラー抽出つき）----
      - name: Archive with xcodebuild (Manual signing)
        script: |
          set -euo pipefail
          ARCHIVE_PATH="$CM_BUILD_DIR/build/ios/App.xcarchive"
          LOG_PATH="$CM_BUILD_DIR/xcode_archive.log"

          echo "== Schemes =="
          xcodebuild -list -workspace ios/App/App.xcworkspace || true

          echo "== Start archive =="
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            -destination 'generic/platform=iOS' \
            DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_NAME" \
            CODE_SIGN_STYLE=Manual \
            archive | tee "$LOG_PATH"

          echo "== First error lines =="
          (grep -n " error: " "$LOG_PATH" || true) | head -n 20

      # ---- IPA 書き出し ----
      - name: Export IPA
        script: |
          set -euo pipefail
          ARCHIVE_PATH="$CM_BUILD_DIR/build/ios/App.xcarchive"
          OUTPUT_DIR="$CM_BUILD_DIR/build/ios/ipa"
          mkdir -p "$OUTPUT_DIR"
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist "$CM_BUILD_DIR/export_options.plist" \
            -exportPath "$OUTPUT_DIR"

      # ---- 反映されたビルド設定を確認 ----
      - name: Show effective build settings (provisioning)
        script: |
          set -o pipefail
          xcodebuild -workspace ios/App/App.xcworkspace -scheme App -showBuildSettings | \
            grep -E "PRODUCT_BUNDLE_IDENTIFIER|DEVELOPMENT_TEAM|CODE_SIGN_STYLE|PROVISIONING_PROFILE_SPECIFIER|PROVISIONING_PROFILE" || true

    artifacts:
      - build/ios/ipa/*.ipa
      - $CM_BUILD_DIR/xcode_archive.log
      - $HOME/Library/Logs/gym/*.log
      - $CM_BUILD_DIR/ios/App/build/**/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
