workflows:
  ios-release:
    name: iOS Release (DogPark JP)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 15.4
      node: 20.11.1
      cocoapods: default
      vars:
        BUNDLE_ID: com.dogparkjp.app
        APPLE_TEAM_ID: 9HT7A6UF4K
        IOS_SCHEME: App

    # App Store Connect の「Integration ID」を使った認証
    integrations:
      app_store_connect: d5ac3012-7133-4adb-afbf-b204d7abc83c

    scripts:
      - name: Install JS deps
        script: |
          npm ci --legacy-peer-deps

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: CocoaPods install (safety)
        script: |
          cd ios/App
          pod repo update
          pod install
          cd ../..

      - name: Bump iOS build number (CFBundleVersion)
        script: |
          cd ios/App
          xcrun agvtool new-version -all $BUILD_NUMBER
          cd ../..

      - name: Build IPA with Xcode (auto-detect workspace/project)
        script: |
          # ios/App 配下の .xcworkspace / .xcodeproj を自動検出して IPA を作成
          xcode-project build-ipa \
            --project-directory ios/App \
            --scheme "$IOS_SCHEME" \
            --allow-provisioning-updates

    artifacts:
      - build/ios/ipa/*.ipa
      - ~/Library/Developer/Xcode/Archives/**/*
      - ios/App/build/*.log

    publishing:
      app_store_connect:
        # TestFlight へアップロード（App Store 提出は off）
        submit_to_testflight: true
        submit_to_app_store: false
        cancel_previous_submissions: true
