workflows:
  ios-release:
    name: iOS Release (DogPark JP)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 15.4
      node: 20.11.1
      cocoapods: default
      vars:
        BUNDLE_ID: com.dogparkjp.app
        APPLE_TEAM_ID: 9HT7A6UF4K
        IOS_SCHEME: App
      groups:
        - supabase
        - codesign

    integrations:
      app_store_connect: "DogParkJP API Key"

    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods
        - ios/Pods

    scripts:
      - name: Install JS deps & build web
        script: |
          npm ci --legacy-peer-deps
          npm run build || npx vite build || true

      - name: Ensure Capacitor iOS platform & sync
        script: |
          npx cap add ios || true
          npx cap sync ios

      - name: CocoaPods install
        script: |
          cd ios/App
          pod repo update || true
          pod install
          cd -

      - name: Fetch signing files & configure keychain
        script: |
          set -e
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain initialize
          # 証明書(p12)をキーチェーンへ確実にインポート
          keychain add-certificates
          xcode-project use-profiles

      - name: Build & Export with raw xcodebuild (print full errors)
        script: |
          set -euo pipefail

          EXPORT_PLIST="$CM_BUILD_DIR/export_options.plist"
          cat > "$EXPORT_PLIST" <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>teamID</key><string>9HT7A6UF4K</string>
            <key>signingStyle</key><string>manual</string>
            <key>signingCertificate</key><string>Apple Distribution</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.dogparkjp.app</key>
              <string>DogParkJP ios_app_store 1758647685</string>
            </dict>
            <key>uploadSymbols</key><true/>
            <key>uploadBitcode</key><false/>
          </dict>
          </plist>
          EOF
          echo "Export options: $EXPORT_PLIST"

          ARCHIVE_PATH="$CM_BUILD_DIR/App.xcarchive"
          IPA_DIR="$CM_BUILD_DIR/ipa"
          mkdir -p "$IPA_DIR"

          echo "== Clean =="
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme "$IOS_SCHEME" \
            -configuration Release \
            clean | tee "$CM_BUILD_DIR/clean.log"

          echo "== Archive =="
          set +e
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme "$IOS_SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="DogParkJP ios_app_store 1758647685" \
            CODE_SIGN_STYLE=Manual \
            "CODE_SIGN_IDENTITY=Apple Distribution" \
            ${CM_KEYCHAIN_PATH:+OTHER_CODE_SIGN_FLAGS="--keychain $CM_KEYCHAIN_PATH"} \
            archive | tee "$CM_BUILD_DIR/archive.log"
          status=${PIPESTATUS[0]}
          set -e
          if [ $status -ne 0 ]; then
            echo "---- tail archive.log (last 200 lines) ----"
            tail -n 200 "$CM_BUILD_DIR/archive.log"
            exit $status
          fi

          echo "== Export =="
          set +e
          xcodebuild \
            -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportPath "$IPA_DIR" \
            -exportOptionsPlist "$EXPORT_PLIST" | tee "$CM_BUILD_DIR/export.log"
          status=${PIPESTATUS[0]}
          set -e
          if [ $status -ne 0 ]; then
            echo "---- tail export.log (last 200 lines) ----"
            tail -n 200 "$CM_BUILD_DIR/export.log"
            exit $status
          fi

          echo "IPA output: $IPA_DIR"

    artifacts:
      - build/ios/ipa/*.ipa
      - ~/Library/Developer/Xcode/Archives/**/*

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
