workflows:
  ios-release:
    name: iOS App Store (Capacitor/Ionic)
    max_build_duration: 60
    instance_type: mac_mini_m1

    integrations:
      app_store_connect: "DogParkJP API Key"   # ← Codemagic に作成済みの統合名

    environment:
      xcode: latest
      cocoapods: default
      node: 20
      vars:
        APP_NAME: "DogPark JP"
        BUNDLE_ID: "com.dogparkjp.app"
        DEVELOPMENT_TEAM: "9HT7A6UF4K"
        # Codemagic > Signing identities > iOS provisioning profiles にあるプロファイル名（拡張子なし）
        PROFILE_NAME: "dogparkjp_app_store_v2"
      groups:
        - supabase
        - codesign

    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - ios/App/Pods
        - ~/.npm

    scripts:
      - name: Show versions
        script: |
          echo "Node: $(node -v)"
          echo "NPM:  $(npm -v)"
          echo "Xcode: $(xcodebuild -version)"

      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps

      - name: Build web assets (Vite/React etc.)
        script: |
          npm run build

      - name: Ensure iOS platform exists
        script: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod repo update
          pod install

      - name: Inspect installed certs & profiles (debug)
        script: |
          echo "== Identities ==" && security find-identity -v -p codesigning || true
          echo "== Provisioning Profiles ==" && ls -la "$HOME/Library/MobileDevice/Provisioning Profiles/" || true

      - name: Fetch profiles & import certs
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates

      - name: Bump iOS build number (CFBundleVersion +1)
        script: |
          PLIST="ios/App/App/Info.plist"
          CUR=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$PLIST" 2>/dev/null || echo 0)
          NEW=$((CUR+1))
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW" "$PLIST"
          echo "New CFBundleVersion: $NEW"

      - name: Apply profile to project (manual pin)
        script: |
          xcode-project use-profiles --project "ios/App/App.xcodeproj" \
            --scheme "App" \
            --profile "$PROFILE_NAME" \
            --code-sign-style "Manual" \
            --team-id "$DEVELOPMENT_TEAM"

      - name: Build IPA with Xcode (recommended flags)
        script: |
          echo "Using PROVISIONING_PROFILE_SPECIFIER=$PROFILE_NAME"
          # サポートからの推奨に従い export-method は指定しない
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App" \
            --archive-flags="-destination 'generic/platform=iOS'"

      - name: Show effective build settings (provisioning)
        script: |
          set -o pipefail
          xcodebuild -workspace ios/App/App.xcworkspace -scheme App -showBuildSettings | \
            grep -E "PRODUCT_BUNDLE_IDENTIFIER|DEVELOPMENT_TEAM|CODE_SIGN_STYLE|PROVISIONING_PROFILE_SPECIFIER|PROVISIONING_PROFILE" || true

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Logs/gym/*.log
      - $CM_BUILD_DIR/ios/App/build/**/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
      scripts:
        - name: Publish to App Store Connect (verbose)
          script: |
            IPA_PATH="$(ls -1 build/ios/ipa/*.ipa | head -n 1)"
            echo "Uploading: $IPA_PATH"
            app-store-connect publish --path "$IPA_PATH" --verbose
