workflows:
  ios-release:
    name: iOS Release (DogPark JP)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 15.4
      node: 20.11.1
      cocoapods: default
      vars:
        BUNDLE_ID: com.dogparkjp.app
        APPLE_TEAM_ID: 9HT7A6UF4K
        IOS_SCHEME: App
        # ← ここに App Store Connect Integration の ID を必ず登録しておく
        # Codemagic の「Environment variables」で APP_STORE_CONNECT_INTEGRATION_ID を Secret として保存済みであること
        # APP_STORE_CONNECT_INTEGRATION_ID: <保存済みの環境変数を使用>

    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods
        - ios/Pods

    scripts:
      - name: Install JS deps & build web
        script: |
          npm ci --legacy-peer-deps
          npm run build || npx vite build || true

      - name: Ensure Capacitor iOS platform & sync
        script: |
          npx cap add ios || true
          npx cap sync ios

      - name: CocoaPods install
        script: |
          cd ios/App
          pod repo update || true
          pod install

      # 署名ファイルを App Store Connect から取得（Integration 方式）
      - name: Fetch signing files & configure keychain
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --integration "$APP_STORE_CONNECT_INTEGRATION_ID"
          keychain initialize

      # 取得したプロファイル/証明書を Xcode プロジェクトへ適用
      - name: Apply signing settings to Xcode project
        script: |
          xcode-project use-profiles \
            --warn-provisioning-updates \
            --target "App" || xcode-project use-profiles --warn-provisioning-updates

      - name: Bump iOS build number (CFBundleVersion)
        script: |
          if [ -d "ios/App/App.xcworkspace" ] || [ -d "ios/App/App.xcodeproj" ]; then
            agvtool new-version -all "$BUILD_NUMBER"
          else
            echo "No Xcode project found, skipping agvtool."
          fi

      - name: Build IPA with Xcode (app-store export)
        script: |
          set -e
          if [ -d "ios/App/App.xcworkspace" ]; then
            xcode-project build-ipa \
              --workspace ios/App/App.xcworkspace \
              --scheme "$IOS_SCHEME" \
              --archive-flags "-destination generic/platform=iOS" \
              --export-method app-store
          elif [ -d "ios/App/App.xcodeproj" ]; then
            xcode-project build-ipa \
              --project ios/App/App.xcodeproj \
              --scheme "$IOS_SCHEME" \
              --archive-flags "-destination generic/platform=iOS" \
              --export-method app-store
          else
            echo "No Xcode project under ios/App/"
            exit 1
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - ~/Library/Developer/Xcode/Archives/**/*

    publishing:
      app_store_connect:
        auth: integration
        integration: $APP_STORE_CONNECT_INTEGRATION_ID
        submit_to_testflight: true
