workflows:
  ios-release:
    name: iOS App Store (Capacitor/Ionic)
    max_build_duration: 60
    instance_type: mac_mini_m1

    integrations:
      app_store_connect: "DogParkJP API Key"

    environment:
      xcode: latest
      cocoapods: default
      node: 20
      vars:
        BUNDLE_ID: com.dogparkjp.app
        APP_NAME: DogPark Japan
        DEVELOPMENT_TEAM: 9HT7A6UF4K
        # Codemagic > Signing identities > iOS provisioning profiles の表示名（拡張子なし）
        PROFILE_NAME: dogparkjp_app_store_v2
      groups:
        - supabase
        - codesign

    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - ios/App/Pods
        - ~/.npm

    scripts:
      - name: Show versions
        script: |
          echo "Node: $(node -v)"
          echo "NPM:  $(npm -v)"

      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps

      - name: Build web assets (Vite)
        script: |
          npm run build

      - name: Ensure iOS platform exists
        script: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod repo update
          pod install

      # --- 証明書/プロファイル取得 → Xcode へ適用 ---
      - name: Fetch profiles & import certs
        script: |
          set -e
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates

      - name: Apply profiles to Xcode project
        script: |
          xcode-project use-profiles

      # 反映状況の確認（任意）
      - name: Show signing settings (debug)
        script: |
          xcode-project show-build-settings --workspace "ios/App/App.xcworkspace" --scheme "App" | \
          grep -E "PRODUCT_BUNDLE_IDENTIFIER|DEVELOPMENT_TEAM|CODE_SIGN_STYLE|PROVISIONING_PROFILE_SPECIFIER|PROVISIONING_PROFILE" || true

      # --- アーカイブ & IPA 作成（サポート推奨フラグを使用）---
      - name: Build IPA with Xcode (after use-profiles)
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App" \
            --archive-flags="-destination 'generic/platform=iOS'"

      # 実際のビルド設定を再確認（任意）
      - name: Show effective build settings (provisioning)
        script: |
          set -o pipefail
          xcodebuild -workspace ios/App/App.xcworkspace -scheme App -showBuildSettings | \
            grep -E "PRODUCT_BUNDLE_IDENTIFIER|DEVELOPMENT_TEAM|CODE_SIGN_STYLE|PROVISIONING_PROFILE_SPECIFIER|PROVISIONING_PROFILE" || true

      # --- App Store Connect へアップロード（詳細ログ付き）---
      - name: Publish to App Store Connect (verbose)
        script: |
          set -e
          app-store-connect publish --path build/ios/ipa/App.ipa --verbose || true
          echo "Transporter logs (if any):"
          ls -la "$HOME/Library/Logs/Transporter" || true

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Logs/gym/*.log
      - $CM_BUILD_DIR/ios/App/build/**/*.log
      - $HOME/Library/Logs/Transporter/*

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
