-- サンプルドッグパークデータの挿入
INSERT INTO dog_parks (
    name,
    description,
    address,
    prefecture,
    city,
    latitude,
    longitude,
    max_capacity,
    current_occupancy,
    hourly_rate,
    is_active,
    is_open,
    opening_hours,
    contact_phone,
    contact_email,
    amenities,
    rules,
    image_urls
) VALUES 
(
    '東京ドッグパーク渋谷',
    '渋谷駅から徒歩5分の便利なドッグパーク。小型犬から大型犬まで安心して遊べる広いスペースを提供しています。',
    '東京都渋谷区渋谷1-1-1',
    '東京都',
    '渋谷区',
    35.6598,
    139.7006,
    20,
    0,
    500,
    true,
    true,
    '9:00-19:00',
    '03-1234-5678',
    'info@shibuya-dogpark.com',
    ARRAY['駐車場', 'トイレ', '水飲み場', 'ベンチ', '屋根付きエリア'],
    ARRAY['リードを外してもOK', '糞の処理は飼い主が責任を持って行う', '攻撃的な犬の入場禁止', '未成年者の単独利用禁止'],
    ARRAY['https://via.placeholder.com/400x300?text=渋谷ドッグパーク']
),
(
    '新宿わんわん広場',
    '新宿の中心部にある緑豊かなドッグパーク。ペットホテル併設で安心です。',
    '東京都新宿区新宿2-2-2',
    '東京都',
    '新宿区',
    35.6938,
    139.7036,
    15,
    0,
    600,
    true,
    true,
    '8:00-20:00',
    '03-2345-6789',
    'contact@shinjuku-dogpark.com',
    ARRAY['ペットホテル', 'トリミング', '獣医師常駐', 'カフェ'],
    ARRAY['予約制', '健康チェック必須', '1時間利用制'],
    ARRAY['https://via.placeholder.com/400x300?text=新宿わんわん広場']
),
(
    '品川ペットランド',
    '品川駅直結の屋内ドッグパーク。天候に左右されずいつでも利用可能。',
    '東京都港区品川3-3-3',
    '東京都',
    '港区',
    35.6284,
    139.7387,
    25,
    0,
    450,
    true,
    true,
    '10:00-22:00',
    '03-3456-7890',
    'info@shinagawa-petland.com',
    ARRAY['屋内施設', 'エアコン完備', 'ペットグッズ販売', '無料WiFi'],
    ARRAY['室内用靴必須', '大型犬は要事前確認', '食べ物持ち込み禁止'],
    ARRAY['https://via.placeholder.com/400x300?text=品川ペットランド']
);

-- 挿入結果の確認
SELECT COUNT(*) as inserted_count FROM dog_parks WHERE name LIKE '%東京%' OR name LIKE '%新宿%' OR name LIKE '%品川%'; 